# --- Основная информация о сайте ---
site_name: Glorp Language
site_url: https://github.com/LecSUSOff/glorp
site_author: 'Alexey'
copyright: 'Copyright © 2025 Alexey Zhukovski'

# --- Ссылка на репозиторий (добавляет иконку GitHub) ---
repo_url: https://github.com/LecSUSOff/glorp/ # Замените
repo_name: 'glorp'

# --- Тема оформления и ее настройки ---
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    # Светлая тема
    - scheme: default
      primary: 'deep orange'
      accent: 'orange'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Темная тема
    - scheme: slate
      primary: 'orange'
      accent: 'deep orange'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top # Добавляет кнопку "Наверх"
    - content.code.copy # Кнопка "Копировать" для блоков кода
    - search.suggest # Автодополнение в поиске

# --- Структура навигации (меню сайта) ---
nav:
  - 'Introduction': 'introduction.md'
  - 'Getting started': 'getting-started.md'
